#!/usr/bin/env bash
# display the domain and subdamain

configureSubdomain() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    configureSubdomain "$2.$1" "$2"
else
    configureSubdomain "www.$1" "www"
    configureSubdomain "lb-01.$1" "lb-01"
    configureSubdomain "web-01.$1" "web-01"
    configureSubdomain "web-02.$1" "web-02"
fi

