#!/usr/bin/env bash
# Debugging the scp command

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_name=$1
user_name=$2
secureshell=$4
address_id=$3

# Debugging: Print variable values
echo "File Name: $file_name"
echo "User Name: $user_name"
echo "SSH Key: $secureshell"
echo "Address ID: $address_id"

# Test the scp command with variable values
scp -o "StrictHostKeyChecking no" -i "$secureshell" "$file_name" "$user_name@$address_id:~/"

