#!/usr/bin/env bash 
# shell script that will help to sending file btn client and server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_name=$1
user_name=$2
secureshell=$4
address_id=$3

scp -o "RestrictHostKeyChecking=no" -i "$secureshell" "$file_name" "$user_name@$address_id:~/"

