#!/usr/bin/env bash
# creating error page

# update and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# make file index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# make rediretion page
marius="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mariusbayizere permanent;"
sudo sed -i "s/server_name _;/$marius/" /etc/nginx/sites-enabled/default

# test if our web is ok
sudo nginx -t

# starting nginx server
sudo service nginx restart
