#!/usr/bin/env bash
# INSTALLING Nginx on port 80

echo -e "installing Nginx\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y


# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# changing the owner of the user 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# to copy to the that path inorder to make the backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# create the content in the page 
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# redirect the user to the youtube 
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# display error meassage when the user access incorrect page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# starting service for the webserver
sudo service nginx restart

echo -e "\nCompleted.\n"
