#!/bin/env bash
# Using what you did for task #0, make your fix short and sweet
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid

