#!/usr/bin/env bash
# Bash script to stop 4-to_infinity_and_beyond process

# Use pgrep with the process name and -f option to search the entire command line
p=$(pgrep -f "bash ./4-to_infinity_and_beyond")

# Terminate the infinite process
if [ -n "$p" ]; then
    kill -15 "$p"
fi

