#!/usr/bin/env bash
# Dispaly information about username,user id and home directory in line of /etc/passwd.

ban="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$ban"
