#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Stop the nginx service
sudo systemctl stop nginx

# Backup the original nginx configuration file
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Replace 'user' directive to run nginx as nginx user
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Add listen directive to listen on all active IPs on port 8080
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Correct file permissions
sudo chmod 644 /etc/nginx/nginx.conf

# Correct file ownership
sudo chown nginx:nginx /etc/nginx/ -R

# Start the nginx service
sudo systemctl start nginx
